---
- ansible.builtin.include_tasks: common.yml

- name: "Restart all containers"
  ansible.builtin.command:
    argv: [podman, compose, restart]
    chdir: "{{ control_homelab_dir }}/apps/{{ item }}"
  loop: "{{ _app_list }}"
