---
- name: Setup glance app directory
  ansible.builtin.file:
    path: "{{ glance_app_dir }}/apps/glance"
    state: directory
    mode: "0755"

- name: Copy glance.yml
  ansible.builtin.copy:
    src: glance.yml
    dest: "{{ glance_app_dir }}/apps/glance/glance.yml"
    backup: true

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ glance_app_dir }}/apps/glance/docker-compose.yml"
    mode: "0644"

- name: Install glance nginx config
  ansible.builtin.template:
    src: nginx-glance.conf.j2
    dest: /etc/nginx/conf.d/glance.conf
    mode: "0644"
  become: true
  notify: reload nginx
