---
- name: Setup podman
  block:
    - name: Install podman
      ansible.builtin.package:
        name: "{{ podman_packages }}"
        state: present
      become: true

    - name: Enable podman socket
      ansible.builtin.systemd:
        name: podman.socket
        scope: user
        enabled: true
        state: started
      failed_when: false
