---
- name: Disable server sleep targets
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: true
  become: true
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
