---
- name: Disable server sleep targets
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: true
  become: true
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target

- name: Create SFTP file drop directory
  ansible.builtin.file:
    path: "{{ server_file_drop_dir }}"
    state: directory
    mode: "0750"
