---
- name: Setup tailscale
  block:
    - name: Check if tailscale is installed
      ansible.builtin.command:
        argv:
          - which
          - tailscale
      register: tailscale_check
      changed_when: false
      failed_when: false

    - name: Install tailscale
      ansible.builtin.shell: "curl -fsSL {{ tailscale_install_url }} | sh"
      args:
        executable: /bin/bash
      become: true
      when: tailscale_check.rc != 0
