---
- name: Install common packages on Fedora
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install common packages on Debian
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Find dotfile directories
  ansible.builtin.find:
    paths: "{{ dotfiles_home_dir }}"
    file_type: directory
    recurse: true
    hidden: true
  register: dotfile_dirs
  delegate_to: localhost
  run_once: true

- name: Create dotfile directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item.path | regex_replace('^' ~ (dotfiles_home_dir | regex_escape) ~ '/', '') }}"
    state: directory
    mode: "0755"
  loop: "{{ dotfile_dirs.files }}"
  when: item.path != dotfiles_home_dir

- name: Find dotfiles
  ansible.builtin.find:
    paths: "{{ dotfiles_home_dir }}"
    file_type: file
    recurse: true
    hidden: true
  register: dotfiles
  delegate_to: localhost
  run_once: true

- name: Copy dotfiles into home
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path | regex_replace('^' ~ (dotfiles_home_dir | regex_escape) ~ '/', '') }}"
    mode: preserve
    backup: true
  loop: "{{ dotfiles.files }}"
