# Prefix key
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable mouse
set -g mouse on

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Custom split commands
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Easy config reload
bind r source-file ~/.config/tmux/tmux.conf

# Easier pane navigation
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Theme (Gruvbox Dark)
set -g status-style bg=#282828,fg=#ebdbb2
set -g window-status-style fg=#928374
set -g window-status-current-style fg=#fb4934,bg=#3c3c3c
set -g pane-border-style fg=#282828
set -g pane-active-border-style fg=#689d6a
set -g message-style bg=#282828,fg=#ebdbb2

# Terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Better escape timings
set -s escape-time 0

# Increase history
set -g history-limit 10000
