---
- name: Setup openwebui app directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/serve/apps/open-webui"
    state: directory
    mode: "0755"

- name: Template openwebui docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ ansible_facts['env']['HOME'] }}/serve/apps/open-webui/docker-compose.yml"
    mode: "0644"

- name: Install openwebui nginx config
  ansible.builtin.template:
    src: nginx-openwebui.conf.j2
    dest: /etc/nginx/conf.d/openwebui.conf
    mode: "0644"
  become: true
  notify: reload nginx
