---
- name: Setup node
  block:
    - name: Install nodejs
      ansible.builtin.package:
        name: "{{ node_packages }}"
        state: present
      become: true

    - name: Install npm global packages
      ansible.builtin.command:
        argv:
          - npm
          - install
          - --global
          - --force
          - --prefix
          - "{{ node_npm_prefix }}"
          - "{{ item }}"
      loop: "{{ node_npm_packages }}"
      changed_when: false
