---
- name: configure pihole dns
  ansible.builtin.command:
    argv:
      - podman
      - exec
      - pihole
      - pihole-FTL
      - --config
      - dns.hosts
      - "{{ homelab_pihole_dns_hosts | to_json }}"
  become: true

- name: configure pihole dhcp
  ansible.builtin.command:
    argv:
      - podman
      - exec
      - pihole
      - pihole-FTL
      - --config
      - misc.dnsmasq_lines
      - "{{ ['dhcp-option=option:dns-server,' ~ (homelab_env.HOMELAB_IP | default(''))] | to_json }}"
  become: true
  when:
    - not homelab_tailscale_only
    - homelab_dhcp_active | bool

- name: enable podman restart service
  ansible.builtin.command:
    argv:
      - systemctl
      - enable
      - --now
      - podman-restart.service
  become: true
  failed_when: false
