---
- name: Setup podman
  block:
    - name: Install podman
      ansible.builtin.package:
        name: "{{ podman_packages }}"
        state: present
      become: true

    - name: Enable lingering for user
      ansible.builtin.command:
        argv: [loginctl, enable-linger, "{{ ansible_facts['env']['USER'] }}"]
      become: true
      args:
        creates: "/var/lib/systemd/linger/{{ ansible_facts['env']['USER'] }}"

    - name: Enable podman socket
      ansible.builtin.systemd_service:
        name: podman.socket
        scope: user
        enabled: true
        state: started
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"

    - name: Enable Podman restart service
      ansible.builtin.systemd_service:
        name: podman-restart.service
        scope: user
        enabled: true
        state: started
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
