---
- name: Setup base packages
  block:
    - name: Load OS-specific variables
      ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

    - name: Install common packages
      ansible.builtin.package:
        name: "{{ base_packages + base_extra_packages }}"
        state: present
      become: true

- name: Setup fastfetch config
  block:
    - name: Create .config/fastfetch directory
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/fastfetch"
        state: directory
        mode: "0755"

    - name: Copy fastfetch config
      ansible.builtin.copy:
        src: .config/fastfetch/config.jsonc
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/fastfetch/config.jsonc"
        backup: true
